pybo/views/search_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash, jsonify
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import SearchForm
from pybo.models import Search_Keyword_list, Search_Result_list

import json # 감정컬러 버튼 생성용 추가
import os
import pandas as pd

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

bp = Blueprint('search', __name__, url_prefix='/search')

# 데이터 베이스에서 검색어 정보를 가져옴
@bp.route('/detail/')
def search_detail():
    form = SearchForm()
    with open(os.path.join(BASE_DIR, '..', 'data/emotion_2depth_colorrange.json'), 'r') as f:
        color_ranges = json.load(f)
    return render_template('search/search_detail.html', form=form, color_ranges=color_ranges)

# Added bp.route for search_form view
@bp.route('/search_form')
def search_form_route():
    form = SearchForm()
    return render_template('search/search_form.html', form=form)


# 검색 결과를 반환하는 함수 - 테스트
def get_search_results(input_keyword):
    with open(os.path.join(BASE_DIR, '..', 'data/book_happy_test.xlsx'), 'rb') as f:
        book_data = pd.read_excel(f, header=0)
    search_results = []
    input_keyword = input_keyword.lower()
    for index, column in book_data.iterrows():
        if input_keyword in column['emotion'].lower() and column['typeName'] == '도서':
            # cover_image = column['coverNo'].lower() +'.jpg'
            image_path = os.path.join(BASE_DIR, '..', 'data/book_happy_test', column['coverNo'] + '.jpg')
            search_results.append(
                {'emotion_keyword': column['emotion'], 'cover_number': column['coverNo'], 'book_name': column['titleInfo'], 'kind': column['typeName'], 'place': column['licText'], 'cover_image': column['coverNo'] + '.jpg'}
            )
    return search_results

# Modified search_result to a route function # #페이지 부분들 삭제하면, 동작함
@bp.route('/search_result', methods=['GET', 'POST'])
def search_result():
    form = SearchForm()
    search_results = []
    if request.method == 'POST' and form.validate_on_submit():
        keyword = form.keyword.data
        print(f"Input keyword: {keyword}")  # Debugging print statement
        search_results = get_search_results(keyword)
        print(f"Search results: {search_results}") # Debugging
    return render_template('search/search_result.html', form=form, search_results=search_results)

# "form" variable added to the function parameter
@bp.route('/emotion_buttons/')
def emotion_buttons():
    form = SearchForm()
    with open(os.path.join(BASE_DIR, '..', 'data/emotion_2depth_colorrange.json'), 'r') as f:
        color_ranges = json.load(f)
    return render_template('search/search_detail.html', form=form, color_ranges=color_ranges)

pybo/templates/search/search_detail.html
{% extends 'base.html' %} {% block content %}

<div class="hero">
  <h1 class="text-center text-success pt-5">인공지능 도서추천사 똑똑</h1>
  <h2 class="text-center text-dark pb-5">
    지금 마음상태에 도움될 도서를 추천해드릴께요!
  </h2>
  <h3 class="text-center text-dark pb-5">마음상태가 어떠신가요?</h3>
</div>

<!-- 검색 입력폼과 버튼 생성하기 start -->
<!-- 아래 컬러버튼 값을 가져오도록 하는 입력칸 -->
<div class="hero container mt-6">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" action="{{ url_for('search.search_result') }}">
        {{ form.hidden_tag() }} {% include "form_errors.html" %}
        <div class="form-group row justify-content-center">
          <div class="col-md-9">
            <input
              id="search-input"
              class="form-control mr-sm-2 text-center h-30"
              type="search"
              placeholder="갑정을 표현해주세요! (예: Suffering, Happy)"
              aria-label="Search"
              name="keyword"
            />
          </div>
          <div class="col-md-3">
            <button
              type="submit"
              class="btn btn-primary"
              onclick="saveSearchKeyword()"
            >
              입력하기
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- 검색 입력폼과 버튼 생성하기 end -->

<!-- 감정단어 버튼 클라우드 start -->
<div class="hero text-center text-dark">
  <p class="text-gray">⬍</p>
  <p>아래 색색의 "감정단어" 버튼을 누르시면,<br/>검색창에 자동으로 입력됩니다.</p>
</div>

<!-- 버튼들을 출력할 영역 start -->
<div class="container" style="width: 80%; margin: 0 auto;">
  <div class="text-center"></div>
  <div id="button-container-test2" class="text-center">
    {% for emotion, sub_emotions in color_ranges.items() %} {% for sub_emotion,
    color_range in sub_emotions.items() %} {% set colors =
    color_range.split(":") %}
    <button
      type="button"
      class="btn btn-primary"
      style="background-color: {{ colors[0] }};"
      onclick="document.getElementById('search-input').value = '{{ sub_emotion }}';"
    >
      {{ sub_emotion }}
    </button>
    {% endfor %} {% endfor %}
  </div>
</div>
<!-- 버튼들을 출력할 영역 end -->
<!-- 감정단어 버튼 클라우드 end -->

<!-- 똑똑숲지기 start -->
<div class="container mt-5" style="width: 80%">
  <div class="row text-center">
    <div class="col-md-4 mb-3">
      <div class="card h-60">
        <a href="https://ebooktree.oopy.io" target="_blanck">
          <img src="./img/3Dprofile_hm.jpg" class="card-img-top" alt="나무영" />
        </a>
        <div class="card-body">
          <h5 class="card-title">나무영</h5>
          <h6 class="card-subtitle mb-2 text-muted">
            (주)독립출판식목일 디발자
          </h6>
          <p class="card-text">
            오늘도 성경과 전자책 무료나눔을 고민하는 소셜벤처러 입니다.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <div class="card h-60">
        <a href="https://github.com/shechren" target="_blanck">
          <img src="./img/3Dprofile_jh.jpg" class="card-img-top" alt="임준혁" />
        </a>
        <div class="card-body">
          <h5 class="card-title">임준혁</h5>
          <h6 class="card-subtitle mb-2 text-muted">
            뚝딱뚝딱 작곡하는 개발러
          </h6>
          <p class="card-text">
            소외된 친구들을 위한 프로그래밍 교육자가 되기를 희망합니다.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <div class="card h-60">
        <a href="https://github.com/lakP44" target="_blanck">
          <img
            src="./img/3Dprofile_lak.jpg"
            class="card-img-top"
            alt="김락형"
          />
        </a>
        <div class="card-body">
          <h5 class="card-title">김락형</h5>
          <h6 class="card-subtitle mb-2 text-muted">
            조곤조곤 코딩하는 개발러
          </h6>
          <p class="card-text">
            AI를 넘어선 fullstack개발자를 꿈꾸고 있습니다.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- 똑똑숲지기 end -->
{% endblock %}

pybo/templates/search/search_form.html
{% extends 'base.html' %}

{% block content %}

    <p>Search Keyword</p>

    <form method="post" action="/search">
      {{ form.csrf_token }}
      {% include "form_errors.html" %}
      <label for="keyword">Keyword:</label>
      <input type="text" id="keyword" name="keyword">
      <input type="submit" value="Search">
    </form>
{% endblock %}

pybo/templates/search/search_result.html
{% extends 'base.html' %} {% block content %}

<h2 class="text-center">Search Result</h2>
<hr />

<div class="container mt-3">
  {% if search_results %}
  <table class="table table-success table-striped">
    <thead>
      <tr>
        <th scope="col" style="width: 20%">책 표지</th>
        <th scope="col" style="width: 20%">도서 제목</th>
        <th scope="col">감정 키워드</th>
        <th scope="col">자료 종류</th>
        <th scope="col">자료 위치</th>
      </tr>
    </thead>
    <tbody>
    {% for search_result in search_results %}
      <tr>
        <td>
          <img src="{{ url_for('static', filename='bookcover/' + search_result.cover_number + '.jpg') }}" alt="{{ search_result.book_name }}" style="width:120px; height:180px;">
        </td>
        <td>{{ search_result.book_name }}</td>
        <td>{{ search_result.emotion_keyword }}</td>
        <td>{{ search_result.kind }}</td>
        <td>{{ search_result.place }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="text-center">검색 결과가 없습니다.</p>
  {% endif %}
</div>

{% endblock %}